name: Rust CI

on:
  push:
    paths:
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"
      - "examples/**/*.rs"
      - "src/**/*.rs"
      - "Cargo.lock"
      - "Cargo.toml"
      - "build.rs"

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: |
          nix develop .#ci --command cargo fmt --all --check

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: |
          nix develop .#ci --command cargo clippy --workspace --tests --all-features -- -Dwarnings

  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: |
          nix develop .#ci --command cargo test --workspace --all-features
