name: Rust CI

on:
  push:
    paths:
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"
      - "examples/**/*.rs"
      - "src/**/*.rs"
      - "Cargo.lock"
      - "Cargo.toml"
      - "build.rs"

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: |
          nix run .#.ci.x86_64-linux.cargo-fmt

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: |
          nix run .#.ci.x86_64-linux.cargo-clippy

  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: |
          nix run .#.ci.x86_64-linux.cargo-test
